adm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from adm.views import Dashboard

urlpatterns = [
    url(r'^$', Dashboard.as_view(),name='dashboard'),
    
]

client/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import ClientList, ClientCreate, ClientDelete, ClientUpdate 

urlpatterns = [
    url(r'^$', ClientList.as_view(),name='clients'),
    url(r'novo$', ClientCreate.as_view(),name='client_new'),
    url(r'editar/(?P<pk>\d+)$', ClientUpdate.as_view(),name='client_update'),
    url(r'excluir/(?P<pk>\d+)$', ClientDelete.as_view(), name='client_delete')

]

sales/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import adm,order,product,client,notification
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'', include('adm.urls',namespace='adm')),
    url(r'^vendas/', include('order.urls',namespace='order')),
    url(r'^clientes/', include('client.urls',namespace='client')),
    url(r'^produtos/', include('product.urls',namespace='product')),
    url(r'', include('notification.urls',namespace='notification'))
]

client/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Client(models.Model):
    name = models.CharField(max_length=200, verbose_name=u"Nome")
    cellphone = models.CharField(max_length=17, null=True, blank=True, verbose_name=u"Telefone")
    email = models.CharField(max_length=100, null=True, blank=True)
    excluded = models.BooleanField(default=False)
    excluded_at = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

client/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'cellphone', 'email']
    def __init__(self,*args,**kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['style'] = 'width:65%'
        self.fields['cellphone'].widget.attrs['style'] = 'width:65%'
        self.fields['email'].widget.attrs['style'] = 'width:65%'
        

client/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Client
from .forms import ClientForm

# Create your views here.


class ClientList(LoginRequiredMixin,ListView):
    model = Client
    def get_queryset(self):
        queryset = Client.objects.filter(excluded=False)
        return queryset
class ClientCreate(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = Client
    form_class = ClientForm
    success_message = "Cliente criado com sucesso"
    success_url = reverse_lazy('client:clients')

class ClientUpdate(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = Client
    form_class = ClientForm
    success_message = "Cliente atualizado com sucesso"
    success_url = reverse_lazy('client:clients')

class ClientDelete(LoginRequiredMixin,DeleteView):
    model = Client
    success_url = reverse_lazy('client:clients')
    
    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)
    # def post(self,request):
    #     pk = request.POST.get('pk')
    #     # import ipdb; ipdb.set_trace()
    #     client = Client.objects.get(pk=pk)
    #     client.excluded = True
    #     client.save()
    #     context = {'mensagem':'Cliente foi excluido'}  #  set your context
    #     return HttpResponse(context)

client/templates/client/client_form.html
{% extends 'core/base.html' %}
{% load bootstrap %}
{% block content %}

    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i> Adicionar Cliente </div>
            <div class="card-body">
            <form method="POST" class="post-form">{% csrf_token %}
                {{ form|bootstrap }}
                <button type="submit" class="save btn btn-default">Salvar</button>
            </form>
            </div>
    </div>

{% endblock %}

client/templates/client/client_list.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="card mb-3">
    <div class="card-header">
      <i class="fa fa-table"></i> Lista de Clientes</div>
    <div class="card-body">
    <div class="btn-group" role="group" aria-label="Basic example">
        <a class="btn btn-info" role="button" href="{% url 'client:client_new' %}">Novo Cliente</a>
    </div>
    <hr size="30">  
      <div class="table-responsive">
        <table class="table table table-sm" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Telefone</th>
              <th>Email</th>
              <th style="max-width:1%">Ações</th> 
            </tr>
          </thead>
        
          <tbody>
            {%for client in object_list%}
            <tr>
                <td>{{client.name}}</td>
                <td>{{client.cellphone}}</td>
                <td>{{client.email}}</td>
                <td>
                    <a style="margin-right:5px" href="{% url 'client:client_update' client.pk %}"><span class="ion-edit"></span></a>
                    <form method="POST" id="form_delete_{{client.pk}}" action="{% url 'client:client_delete' client.pk %}">
                      {% csrf_token %}
                      <a onclick="deleteItem({{client.pk}})" href="#" id="btn_delete"><span class="ion-close-round"></span></a>
                    </form>
                </td>
            </tr>    
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</div>

{% if messages %}
    {% for m in messages %}
    <div id="message" style="visibility: hidden">
      <p>{{m}}</p>
    </div>
    {% endfor %}
{% endif %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script>

  
  $( document ).ready(function() {
    var message = $('#message p').text();
    if(message){
      toastr.options.timeOut = 10000;
      return toastr.success(message);
    }
    if(localStorage.getItem("Deleted"))
    {
      localStorage.clear();
      toastr.options.timeOut = 10000;
      return toastr.success('O item foi excluído');
    }
  });
  
  function deleteItem(pk){
      var form_id = 'form_delete_'+pk;
      bootbox.confirm({
      message: "Você deseja realmente excluir esse cliente?",
      buttons: {
          confirm: {
              label: 'Sim',
              className: 'btn-success'
          },
          cancel: {
              label: 'Não',
              className: 'btn-danger'
          }
      },
      callback: function (result) {
          if(result){
            document.getElementById(form_id).submit(); 
          }
          
      }
      });
  }



</script>

{% endblock %}