adm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from adm.views import Dashboard

urlpatterns = [
    url(r'^$', Dashboard.as_view(),name='dashboard'),
    
]

product/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import ProductList, ProductCreate, ProductUpdate, ProductDelete, get_price

urlpatterns = [
    url(r'^$', ProductList.as_view(),name='products'),
    url(r'novo$', ProductCreate.as_view(),name='product_new'),
    url(r'editar/(?P<pk>\d+)$', ProductUpdate.as_view(),name='product_update'),
    url(r'excluir/(?P<pk>\d+)$', ProductDelete.as_view(), name='product_delete'),
    url(r'preco-produto/$', get_price, name='get_price'),
]

sales/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import adm,order,product,client,notification
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'', include('adm.urls',namespace='adm')),
    url(r'^vendas/', include('order.urls',namespace='order')),
    url(r'^clientes/', include('client.urls',namespace='client')),
    url(r'^produtos/', include('product.urls',namespace='product')),
    url(r'', include('notification.urls',namespace='notification'))
]

product/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name=u"Nome")
    cost_price = models.DecimalField(max_digits=6, decimal_places=2,null=True, verbose_name=u"Preço de Custo")
    sale_price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name=u"Preço de Venda")
    description = models.TextField(verbose_name=u"Descrição",blank=True,null=False)
    excluded = models.BooleanField(default=False)
    excluded_at = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

product/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'sale_price', 'cost_price', 'description']
    def __init__(self,*args,**kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['style'] = 'width:65%'
        self.fields['sale_price'].widget.attrs['style'] = 'width:30%'
        self.fields['cost_price'].widget.attrs['style'] = 'width:30%'
        self.fields['description'].widget.attrs['style'] = 'width:65%;height:20%'
        

product/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, reverse
from django.views import View
from .models import Product
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import ProductForm
from django.http import JsonResponse

# Create your views here.

class ProductList(LoginRequiredMixin,ListView):
    model = Product
    def get_queryset(self):
        queryset = Product.objects.filter(excluded=False)
        return queryset

class ProductCreate(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = Product
    form_class = ProductForm
    success_message = "Produto criado com sucesso"
    success_url = reverse_lazy('product:products')
    
class ProductUpdate(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = Product
    form_class = form_class = ProductForm
    success_message = "Produto atualizado com sucesso"
    success_url = reverse_lazy('product:products')
    
class ProductDelete(LoginRequiredMixin,DeleteView):
    model = Product
    success_url = reverse_lazy('product:products')
    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

def get_price(request):
    # import ipdb;ipdb.set_trace()
    id = request.POST.get('id')

    product = Product.objects.get(pk=id)
    data = {'price':product.sale_price}
    return JsonResponse(data)


        

product/templates/product/product_confirm_delete.html
<form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input type="submit" value="Submit" />
    </form>

product/templates/product/product_form.html
{% extends 'core/base.html' %}
{% load bootstrap %}
{% block content %}

    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i> Adicionar Produto </div>
            <div class="card-body">
            <form method="POST" class="post-form">{% csrf_token %}
                {{ form|bootstrap }}
                <button type="submit" class="save btn btn-default">Salvar</button>
            </form>
            </div>
    </div>

{% endblock %}

product/templates/product/product_list.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="card mb-3">
    <div class="card-header">
      <i class="fa fa-table"></i> Lista de Produtos</div>
    <div class="card-body">
    <div class="btn-group" role="group" aria-label="Basic example">
        <a class="btn btn-info" role="button" href="{% url 'product:product_new' %}">Novo Produto</a>
    </div>
    <hr size="30"> 
      <div class="table-responsive">
        <table class="table table table-sm" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Valor de Venda</th>
              <th>Valor da Custo</th>
              <th>Descrição</th>
              <th style="max-width:1%">Ações</th> 
            </tr>
          </thead>
        
          <tbody>
            {%for product in object_list%}
            <tr>
                    <td>{{product.name}}</td>
                    <td>R$ {{product.sale_price}}</td>
                    <td>R$ {{product.cost_price}}</td>
                    <td>{{product.description}}</td>
                    <td>
                        <a style="margin-right:5px" href="{% url 'product:product_update' product.pk %}"><span class="ion-edit"></span></a>
                        <form method="POST" id="form_delete_{{product.pk}}" action="{% url 'product:product_delete' product.pk %}">
                           {% csrf_token %}
                           <a onclick="deleteItem({{product.pk}})" href="#" id="btn_delete"><span class="ion-close-round"></span></a>
                        </form>
                    </td>
            </tr>    
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</div>

{% if messages %}
    {% for m in messages %}
    <div id="message" style="visibility: hidden">
      <p>{{m}}</p>
    </div>
    {% endfor %}
{% endif %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script>

  
  $( document ).ready(function() {
    var message = $('#message p').text();
    if(message){
      toastr.options.timeOut = 10000;
      return toastr.success(message);
    }
    if(localStorage.getItem("Deleted"))
    {
      localStorage.clear();
      toastr.options.timeOut = 10000;
      return toastr.success('O item foi excluído');
    }
  });
  
   function deleteItem(pk){
      var form_id = 'form_delete_'+pk;
      bootbox.confirm({
      message: "Você deseja realmente excluir esse produto?",
      buttons: {
          confirm: {
              label: 'Sim',
              className: 'btn-success'
          },
          cancel: {
              label: 'Não',
              className: 'btn-danger'
          }
      },
      callback: function (result) {
          if(result){
            document.getElementById(form_id).submit();  
          }
          
      }
      });
  }


</script>
{% endblock %}

product/templates/product/products.html
{% extends 'core/base.html' %}

{% block content %}

<div class="card mb-3">
    <div class="card-header">
      <i class="fa fa-table"></i> Lista de Produtos</div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>                   
              <th>Nome</th>
              <th>Valor de Venda</th>
              <th>Valor da Custo</th>
              <th>Descrição</th>
            </tr>
          </thead>
        
          <tbody>
            {%for product in products%}
            <tr>
                    <td>{{product.name}}</td>
                    <td>R$ {{product.sale_price}}</td>
                    <td>R$ {{product.cost_price}}</td>
                    <td>{{product.description}}</td>
            </tr>    
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</div>

{% endblock %}