adm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from adm.views import Dashboard

urlpatterns = [
    url(r'^$', Dashboard.as_view(),name='dashboard'),
    
]

client/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import ClientList, ClientCreate, ClientDelete, ClientUpdate 

urlpatterns = [
    url(r'^$', ClientList.as_view(),name='clients'),
    url(r'novo$', ClientCreate.as_view(),name='client_new'),
    url(r'editar/(?P<pk>\d+)$', ClientUpdate.as_view(),name='client_update'),
    url(r'excluir/(?P<pk>\d+)$', ClientDelete.as_view(), name='client_delete')

]

order/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from order.views import OrderList, OrderCreate, OrderDelete, OrderUpdate

urlpatterns = [
    url(r'^$', OrderList.as_view(),name='orders'),
    url(r'novo$', OrderCreate.as_view(),name='order_new'),
    url(r'editar/(?P<pk>\d+)$', OrderUpdate.as_view(),name='order_update'),
    url(r'excluir/(?P<pk>\d+)$',OrderDelete.as_view(), name='order_delete')
    # url(r'excluir$', OrderDelete.as_view(), name='order_delete')
    
]

product/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import ProductList, ProductCreate, ProductUpdate, ProductDelete, get_price

urlpatterns = [
    url(r'^$', ProductList.as_view(),name='products'),
    url(r'novo$', ProductCreate.as_view(),name='product_new'),
    url(r'editar/(?P<pk>\d+)$', ProductUpdate.as_view(),name='product_update'),
    url(r'excluir/(?P<pk>\d+)$', ProductDelete.as_view(), name='product_delete'),
    url(r'preco-produto/$', get_price, name='get_price'),
]

sales/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import adm,order,product,client,notification
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'', include('adm.urls',namespace='adm')),
    url(r'^vendas/', include('order.urls',namespace='order')),
    url(r'^clientes/', include('client.urls',namespace='client')),
    url(r'^produtos/', include('product.urls',namespace='product')),
    url(r'', include('notification.urls',namespace='notification'))
]

client/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Client(models.Model):
    name = models.CharField(max_length=200, verbose_name=u"Nome")
    cellphone = models.CharField(max_length=17, null=True, blank=True, verbose_name=u"Telefone")
    email = models.CharField(max_length=100, null=True, blank=True)
    excluded = models.BooleanField(default=False)
    excluded_at = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

order/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

from product.models import Product

from datetime import datetime

from client.models import Client

from .utils import CHOICES_PAYMENT

class Order(models.Model):
    product = models.ForeignKey(Product, verbose_name=u"Produto")
    client = models.ForeignKey(Client, verbose_name=u"Cliente")
    quantity = models.IntegerField(verbose_name=u"Quantidade")
    description = models.TextField(null=True, blank=True, verbose_name=u"Descrição")
    sale_price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name=u"Preço de Venda (R$)")
    delivered = models.BooleanField(default=False, blank=True, verbose_name=u"Entregue")
    canceled = models.BooleanField(default=True, blank=True, verbose_name=u"Cancelado")
    order_date = models.DateTimeField(default=timezone.now, verbose_name=u"Data do Pedido")
    delivered_date = models.DateTimeField(default=timezone.now, verbose_name=u"Data de Entrega")
    payment_form = models.IntegerField(choices=CHOICES_PAYMENT, null=True, blank=True, verbose_name=u"Forma de pagamento")
    paid_out = models.BooleanField(default=False)
    excluded = models.BooleanField(default=False)
    excluded_at = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} - {}'.format(self.product,self.client)

order/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Order
from django.conf import settings


class OrderForm(forms.ModelForm):
    delivered = forms.ChoiceField(
        label='Entregue?', required=False, widget=forms.CheckboxInput,
        choices=((True, 'Sim'), (False, 'Não'))
    )
    canceled = forms.ChoiceField(
        label='Cancelado?', required=False, widget=forms.CheckboxInput,
        choices=((True, 'Sim'), (False, 'Não'))
    )

    paid_out = forms.ChoiceField(
        label='Pago?', required=False, widget=forms.CheckboxInput,
        choices=((True, 'Sim'), (False, 'Não'))
    )

    class Meta:
        model = Order
        fields = [
            'product', 'client', 'quantity', 'sale_price', 'description',
            'delivered', 'canceled',
            'delivered_date', 'order_date', 'payment_form',
            'paid_out'
        ]
        widgets = {
            'delivered_date': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'datepicker', 'id': 'data_delivered'}
            ),
            'order_date': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'datepicker', 'id': 'data_order'}
            )
        }

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['product'].widget.attrs['style'] = 'width:65%'
        self.fields['client'].widget.attrs['style'] = 'width:65%'
        self.fields['quantity'].widget.attrs['style'] = 'width:20%'
        self.fields['delivered_date'].widget.attrs['style'] = 'width:30%'
        self.fields['order_date'].widget.attrs['style'] = 'width:30%'
        self.fields['sale_price'].widget.attrs['style'] = 'width:30%'
        self.fields['payment_form'].widget.attrs['style'] = 'width:30%'
        self.fields['description'].widget.attrs['style'] = 'width:65%;height:20%'
        self.fields['delivered_date'].input_formats = ['%d/%m/%Y']
        self.fields['order_date'].input_formats = ['%d/%m/%Y']

order/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order
from .forms import OrderForm

# Create your views here.


class OrderList(LoginRequiredMixin,ListView):
    model = Order
    def get_queryset(self):
        queryset = Order.objects.filter(excluded=False)
        return queryset
class OrderCreate(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = Order
    form_class = OrderForm
    success_message = "Venda criado com sucesso"
    success_url = reverse_lazy('order:orders')
    
class OrderUpdate(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = Order
    form_class = OrderForm
    success_message = "Venda atualizado com sucesso"
    success_url = reverse_lazy('order:orders')
    
class OrderDelete(LoginRequiredMixin,SuccessMessageMixin,DeleteView):
    model = Order
    success_message = "Venda excluída com sucesso"
    success_url = reverse_lazy('order:orders')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    # def post(self, *args, **kwargs):
    #     import ipdb;ipdb.set_trace()
    #     pass
 

order/templates/order/order_form.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% block content %}

    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i> Adicionar Venda </div>
            <div class="card-body">
            <form method="POST" class="post-form">{% csrf_token %}
                {% for field in form %}

                    {% if field.name == 'client' %}
                        {{field | bootstrap}}
                        <button class="save btn btn-default" type="button" onclick="openModal()">Criar Cliente</button>
                        <hr>
                    {% else %}
                        {{field | bootstrap}}
                    {% endif %}

                {% endfor %}
                <input type="hidden" id="hid" name="hiddenField" class="hiddenField"/> 

                <button type="submit" class="save btn btn-primary">Salvar</button>
            </form>
            </div>
    </div>


        <!-- Modal -->
    <div class="modal" id="modalClient" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Criando Cliente</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form method="POST" class="post-form" id="form-client">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label  " for="id_name">Nome</label>
                    <div class=" ">
                        <input type="text" name="name" maxlength="200" style="width:65%" class=" form-control" required="" id="id_name">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label  " for="id_cellphone">Telefone</label>
                    <div class=" ">
                        <input type="text" name="cellphone" maxlength="17" style="width:65%" class=" form-control" id="id_cellphone">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label  " for="id_email">Email</label>
                    <div class=" ">
                        <input type="text" name="email" maxlength="100" style="width:65%" class=" form-control" required="" id="id_email">
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" onclick="formClient()" class="btn btn-primary">Salvar</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </div>
            </form>
          </div>

        </div>
      </div>
    </div>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <script>
        function openModal(){
            $("#modalClient").modal()
        }
        function formClient(){
            $.ajax({
              type: "POST",
              url: '{% url "client:client_new" %}',
              data: $('#form-client').serialize(),
              success: function( response ) {
                location.reload();
              }
            });
        }

        $("#id_product").change(function () {
          var id = $( "#id_product option:selected" ).val();
          $.ajax({
            type: "POST",
            url: "{% url 'product:get_price' %}",
            data: {
              'id': id,
              'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            dataType: 'json',
            success: function (data) {
              if (data.price) {
                $( "#id_sale_price" ).val(data.price); 
                $( "#hid" ).val(data.price);  
              }
            }
          });

        });

        $("#id_quantity").change(function () {
            var quantity = parseFloat($(this).val());
            var price = parseFloat($('#hid').val());
            $('#id_sale_price').val(quantity*price);

        });

    </script>
    <script type="text/javascript">
        $(document).ready(function() {
           $('#data_delivered').datepicker({ dateFormat: 'dd/mm/yy' });
           $('#data_order').datepicker({ dateFormat: 'dd/mm/yy' });
        });
    </script>


{% endblock %}

order/templates/order/order_list.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% load tz %}
{% block content %}



<div class="card mb-3">
    <div class="card-header">
      <i class="fa fa-table"></i> Lista de Vendas</div>
    <div class="card-body">
    <div class="btn-group" role="group" aria-label="Basic example">
        <a class="btn btn-info" role="button" href="{% url 'order:order_new' %}">Nova Venda</a>
    </div>
    <hr size="30">
      <div class="table-responsive">
        <table class="table table-sm" id="dataTable" width="100%" style="font-size:15px" cellspacing="0">
          <thead>
            <tr>
              <th>Data do Pedido</th>
              <th>Cliente</th>
              <th>Valor da Venda</th>
              <th>Produto</th>
              <th>Quantidade</th>
              <th>Descrição</th>
              <th>Data de Entrega</th>
              <th>Entregue</th>
              <th>Cancelado</th>
              <th style="max-width:1%">Ações</th>
            </tr>
          </thead>

          <tbody>
            {%for order in object_list%}
            {% if order.delivered == True %}
              <tr class="table-success">
            {% else %}
              <tr class="table-danger">
            {% endif %}

                    <td>{{order.order_date | date:'d-m-Y'}}</td>
                    <td>{{order.client.name}}</td>
                    <td>{{order.sale_price}}</td>
                    <td>{{order.product.name}}</td>
                    <td>{{order.quantity}}</td>
                    <td>{{order.description}}</td>
                    <td>{{order.delivered_date | date:'d-m-Y'}}</td>

                    {% if order.delivered == True %}
                        <td align="center"><i class="fa fa-fw fa-check"></i></span></td>
                    {% else %}
                        <td align="center"><i class="fa fa-fw fa-minus"></i></span></td>
                    {% endif %}
                    {% if order.canceled == True %}
                        <td align="center"><i class="fa fa-fw fa-close"></i></span></td>
                    {% else %}
                        <td align="center"><i class="fa fa-fw fa-minus"></i></span></td>
                    {% endif %}

                    <td>
                        <a style="margin-right:5px" href="{% url 'order:order_update' order.pk %}"><span class="ion-edit" style="color:#000000"></span></a>
                        <form method="POST" id="form_delete_{{order.pk}}" action="{% url 'order:order_delete' order.pk %}">
                           {% csrf_token %}
                           <a onclick="deleteItem({{order.pk}})" href="#" id="btn_delete"><span class="ion-close-round" style="color:#000000"></span></a>
                        </form>
                    </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</div>

{% if messages %}
    {% for m in messages %}
    <div id="message" style="visibility: hidden">
      <p>{{m}}</p>
    </div>
    {% endfor %}
{% endif %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script>


  $( document ).ready(function() {
    var message = $('#message p').text();
    if(message){
      toastr.options.timeOut = 10000;
      return toastr.success(message);
    }
    if(localStorage.getItem("Deleted"))
    {
      localStorage.clear();
      toastr.options.timeOut = 10000;
      return toastr.success('O item foi excluido');
    }
  });


  function deleteItem(pk){
      var form_id = 'form_delete_'+pk;
      bootbox.confirm({
      message: "Você deseja realmente excluir essa venda?",
      buttons: {
          confirm: {
              label: 'Sim',
              className: 'btn-success'
          },
          cancel: {
              label: 'Não',
              className: 'btn-danger'
          }
      },
      callback: function (result) {
          if(result){
            document.getElementById(form_id).submit();
          }

      }
      });
  }


</script>

{% endblock %}

order/templates/order/orders.html
{% extends 'core/base.html' %}

{% block content %}

<div class="card mb-3">
    <div class="card-header">
      <i class="fa fa-table"></i> Lista de Vendas</div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>                   
              <th>Data do Pedido</th>
              <th>Cliente</th>
              <th>Valor da Venda</th>
              <th>Produto</th>
              <th>Quantidade</th>
              <th>Descrição</th>
              <th>Data de Entrega</th>
              <th>Entregue</th>
              <th>Cancelado</th>
            </tr>
          </thead>
        
          <tbody>
            {%for order in orders%}
            <tr>
                    <td>{{order.order_date}}</td>
                    <td>{{order.client.name}}</td>
                    <td>{{order.sale_price}}</td>
                    <td>{{order.product.name}}</td>
                    <td>{{order.quantity}}</td>
                    <td>{{order.description}}</td>
                    <td>{{order.delivered_date}}</td>
                   
                    {% if order.delivered == True %}
                        <td align="center"><i class="fa fa-fw fa-check"></i></span></td>
                    {% else %}
                        <td align="center"><i class="fa fa-fw fa-minus"></i></span></td>
                    {% endif %}
                    {% if order.canceled == True %}
                        <td align="center"><i class="fa fa-fw fa-close"></i></span></td>
                    {% else %}
                        <td align="center"><i class="fa fa-fw fa-minus"></i></span></td>
                    {% endif %}
            </tr>    
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</div>

{% endblock %}